### ISSUE TITLE
Move main code base over to new repository

### ISSUE THREAD

**Issue by lcchapman** [nvs-group/epic#4]
Put the latest code into the new EPIC repository along with active issues.

**Comment by chapmjs** [comment]
In order to create a clean transfer of files on the server, I am going to create a new link to the epic app, which as of right now is the same code as the R_Training version of the app.

The bit.ly link  http://bit.ly/nvsapp points to the R_Training version of the app and is still available directly at http://systemsresearch.ddns.net:3838/R_Training/master%20online%20app/

I have setup a new bitly link will redirect to this new repository - EPIC - [http://bit.ly/nvsepic](http://bit.ly/nvsepic).  The direct link to this repository is:
[http://systemsresearch.ddns.net:3838/epic/](http://systemsresearch.ddns.net:3838/epic/)

**Comment by chapmjs** [comment]
Closing issue
